name: Deploy to AWS

on:
  push:
    branches:
      - main  # For production
      - develop  # For development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd cdk
          npm install

      - name: Get Changed Services
        id: changed_services
        run: |
          git diff --name-only HEAD^ HEAD | grep 'repository/' | awk -F/ '{print $2}' | sort | uniq > services.txt
          echo "services=$(cat services.txt | tr '\n' ',')" >> $GITHUB_ENV

      - name: Deploy Services
        run: |
          for service in $(echo ${{ env.services }} | tr ',' '\n')
          do
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              # Deploy to production
              npx cdk deploy ${service}-Stack-Prod --require-approval never
            elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
              # Deploy to development
              npx cdk deploy ${service}-Stack-Dev --require-approval never
            fi
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ca-central-1
